server:
  port: 8989


spring:
  application:
    name: gateway
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: user_route
#          uri: http://localhost:9999/
          uri: lb://users
          predicates:
            - Path=/user/**
          filters:
            - AddResponseHeader=username,lzc
        - id: product_route
#          uri: http://localhost:9997/
          uri: lb://products
          predicates:
            - Path=/product/**
      discovery:
        locator:
          enabled: true #开启动态获取consul中的服务群

management:
  endpoints:
    web:
      exposure:
        include: "*"